[package]
name = "kairos-trie"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[features]
default = ["std"]
std = []

[profile.test]
opt-level = 3
debug-assertions = true
overflow-checks = true


[dependencies]
sha2 = "0.10"
bumpalo = "3"

[dev-dependencies]
proptest = "1"
