[workspace]

resolver = "2"

members = [
	"kairos-trie",
	"kairos-trie/trie-test-utils",
	"zkvm-merkle-btree",
	"zkvm-merkle-btree/btree-test-utils",
	"fuzz",
]


[profile.test]
opt-level = 3
debug-assertions = true
overflow-checks = true
