[package]
name = "kairos-trie"
version = "0.1.0"
edition = "2021"

[features]
# default = ["std"]
std = []

[dependencies]
sha2 = "0.10"
bumpalo = "3"
ouroboros = "0.18"

[dev-dependencies]
proptest = "1"
